Raahi/urls.py
from django.contrib import admin
from django.urls import include, re_path as url, path
from django.conf import settings
from django.views.static import serve
from .views import *
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('master_data.urls')),
    path('', include('sims.urls')),
    path('', include('dashboard.urls')),
    path('', login_view, name="login"),
    path('', include('reports.urls', namespace='reports')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('sidebar/', sidebar_view, name="sidebar"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('dashboard/', dashboard, name="dashboard"),
    path('form_validate/', form_validate, name="form_validate"),
    path('send_login_email/', send_login_email, name="send_login_email"),
    url(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),

    
]

sims/urls.py
from django.urls import path
from .views import *
from . telecalling import *
from . orders import *

urlpatterns = [
    path('orderrequest_list/', orderrequest_list,name='orderrequest_list'),
    path('add_orderdetails/', add_orderdetails,name='add_orderdetails'),
    path('change_order_status/<str:model>/<int:id>/<str:action>/', change_order_status, name='change_order_status'),
    path('orderdelivery_list/', orderdelivery_list,name='orderdelivery_list'),
    path('add_deliverydetails/', add_deliverydetails,name='add_deliverydetails'),
    path('orders/', orders,name='orders'),
    path('edit_orders/<id>/', edit_orders,name='edit_orders'),
    path('update_order_status/<order_id>/<order_status_id>/', update_order_status,name='update_order_status'),
    path('add_orders/', add_orders,name='add_orders'),
    path('edit_orders_new/<id>/', edit_orders_new,name='edit_orders_new'),
    path('delete_orders/<id>/', delete_orders,name='delete_orders'),
    path('order_details_edit/<id>/', order_details_edit,name='order_details_edit'),
    path("ajax-reject/<reject_id>/<remark>", reject_remark, name="reject_remark"),
    path("add_invoice_awb_no/<order_id>/<invoice_no>/<awb_no>/<invoice_date>/<invoice_value>/<courier_name>/", add_invoice_awb_no, name="add_invoice_awb_no"),

    path('camp_list/', camp_list,name='camp_list'),
    path('camp_date_update/<camp_id>/<date>/<reason>/', camp_date_update,name='camp_date_update'),
    path('add_camp/', add_camp,name='add_camp'),
    path('edit_camp/<id>', edit_camp,name='edit_camp'),
    path('<id>/delete_camp/', delete_camp,name='delete_camp'),

    path('drop_check/', drop_check,name='drop_check'),
    path('order_receipt/', order_receipt,name='order_receipt'),
    path('edit_order_receipt/<id>/', edit_order_receipt,name='edit_order_receipt'),
    path('edit_deliverydetails/<id>/', edit_deliverydetails,name='edit_deliverydetails'),
    path('calculate_damagedetails/<order_id>/', calculate_damagedetails,name='calculate_damagedetails'),

    path('custom-order-request/', custom_order_request,name='custom_order_request'),
    path('generate-order-details/', generate_order_details,name='generate_order_details'),
    path('edit_orders_custom/<order_id>/', generate_order_details,name='edit_orders_custom'),
    path('update_custom_received/<order_id>/<invoice_nos>/', update_custom_received,name='update_custom_received'),
    
    # Patient
    path('patient_list/', patient_list,name='patient_list'),
    path('patient-details/<uuid>/', patient_details,name='patient_details'),
    path('screening_list/', screening_list,name='screening_list'),

    # Telecalling
    path('spectacle-list/', spectacle_list,name='spectacle_list'),
    path('spectacle-details/<uuid>/', spectacle_details,name='spectacle_details'),
    path('add-questions/', add_questions,name='add_questions'),
    path('cataract-list/', cataract_list,name='cataract_list'),
    path('cataract-details/<uuid>/', cataract_details,name='cataract_details'),
    path('cataract_patient-details/<uuid>/', cataract_patient_details,name='cataract_patient_details'),
    path('spectacle_patient-details/<uuid>/', spectacle_patient_details,name='spectacle_patient_details'),

    # Glass
    path('glass-list-pending/', glass_list_pending,name='glass_list_pending'),
    path('glass-list-ready/', glass_list_ready,name='glass_list_ready'),
    path('glass-list-delivered/', glass_list_delivered,name='glass_list_delivered'),
    path('update_glass_followup_status/<patient_id>/<followup_status_id>/', update_glass_followup_status,name='update_glass_followup_status'),

    path('qr-code/',qr_code_generation, name='qr_code_generation'),
    path('data-freeze/',data_freeze, name='data_freeze'),
    path('data-freeze-patients/<data_freeze_id>/',data_freezed_patients, name='data_freezed_patients'),
    path('approve-patient/<data_freeze_id>/', approve_patient,name='approve_patient'),
    path('export_order_details_to_excel/<int:order_id>/', export_order_details_to_excel, name='export_order_details_to_excel'),

]

sims/models.py
from django.db import models
from master_data.models import *
from django.contrib.auth.models import User, Group
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime, timedelta

# Create your models here.
YES_NO_CHOICE = (
        (1, 'YES'),
        (2, 'NO'),
        )

REPLY_CHOICE = (
        (1, 'YES'),
        (2, 'NO'),
        (3, 'NA'),
        )
class Product(BaseContent):
    name = models.CharField(max_length=150)

    class Meta:
        verbose_name_plural = "Product"

    def __str__(self):
        return self.name

class Camp(BaseContent):
    uuid = models.CharField(max_length=150, unique=True, db_index=True, null= True,blank=True)
    name = models.CharField(max_length=150)
    code = models.CharField(max_length=150)
    date = models.DateField() 
    ssmis_id = models.PositiveIntegerField(default=0,null=True, blank=True)
    location = models.CharField(max_length=150)
    address = models.CharField(max_length=150,null= True,blank=True)
    village = models.CharField(max_length=150,null= True,blank=True)
    block = models.CharField(max_length=150,null= True,blank=True)
    district = models.ForeignKey(District, on_delete=models.DO_NOTHING)
    expected_glass_prescription = models.CharField(max_length=150,null= True,blank=True)
    expected_refer_surgeries = models.CharField(max_length=150,null= True,blank=True)
    expected_camp_OPD = models.CharField(max_length=150,null= True,blank=True)
    donor = models.ForeignKey(Donor, on_delete=models.DO_NOTHING)
    vision_center = models.ForeignKey(VisionCenter, on_delete=models.DO_NOTHING,null= True,blank=True)
    coordinator_name =  models.CharField(max_length=150,null= True,blank=True)
    coordinator_mobile_no = models.CharField(max_length=10,null= True,blank=True)
    exclusive_camp = models.IntegerField(choices=YES_NO_CHOICE, default=1)
    partner = models.ForeignKey(Partner, on_delete=models.DO_NOTHING,null= True,blank=True)
    delay_reason = models.TextField(null=True,blank=True)
    start_time = models.TimeField(null=True,blank=True)
    end_time = models.TimeField(null=True,blank=True)
    
    class Meta:
        verbose_name_plural = "Camp"

    def __str__(self):
        return self.name    

    
    def get_start_end_date(self):
        try:
            patients = Patient.objects.filter(status=2,camp_id=self.id).order_by('server_created_on')
            if patients.exists():
                start_date = patients.first().server_created_on
                end_date = patients.last().server_created_on
                return start_date, end_date
            else:
                return None, None
        except ObjectDoesNotExist:
            return None, None

    def get_camp(self):
        try:
            camp = OrderRequest.objects.filter(camp_id=self.id).first()
        except ObjectDoesNotExist:
            camp = None
        return camp


    def get_approved_status(self):
        from dateutil.relativedelta import relativedelta
        current_date = datetime.now().date()
        syn_date = current_date + relativedelta(months=1)
        start_date = current_date.strftime('%Y-%m-06')
        end_date = syn_date.strftime('%Y-%m-05')
        
        no_of_patients_created = Patient.objects.filter(camp_id=self.id, app_created_at__range=(start_date, end_date))
        no_of_patients_to_be_verfied = no_of_patients_created.filter(server_created_on__gt=end_date, status=3)
        try:
            approved_status = no_of_patients_created.order_by('approved_on').first() 
        except:
            approved_status = None
        return approved_status

    def get_unsync_patient(self):
        current_date = datetime.now().date()        
        start_date = datetime(current_date.year, current_date.month, 1).date()
        next_month_start = datetime(current_date.year, current_date.month, 1) + timedelta(days=32)
        end_date = (next_month_start - timedelta(days=next_month_start.day)).date()
        try:
            product = Patient.objects.filter(camp_id=self.id)
        except ObjectDoesNotExist:
            product = None
        return product

    def get_syn_count(self):
        from dateutil.relativedelta import relativedelta
        current_date = datetime.now().date()
        syn_date = current_date + relativedelta(months=1)
        start_date = current_date.strftime('%Y-%m-06')
        end_date = syn_date.strftime('%Y-%m-05')
        
        no_of_patients_created = Patient.objects.filter(camp_id=self.id, app_created_at__range=(start_date, end_date))
        no_of_patients_to_be_verfied = no_of_patients_created.filter(server_created_on__gt=end_date, status=3)

        # Screening Count
        no_of_screening_created= Screening.objects.filter(patient_uuid__in=no_of_patients_created.values_list('uuid'),app_created_at__range=(start_date, end_date))
        no_of_screening_to_be_verfied = no_of_screening_created.filter(server_created_on__gt=end_date, status=3)

        # Family Member Count
        no_of_family_member_created = FamilyMember.objects.filter(screening_uuid__in=no_of_screening_created.values_list('uuid'),app_created_at__range=(start_date, end_date))
        no_of_family_member_to_be_verfied = no_of_family_member_created.filter(server_created_on__gt=start_date, status=3)

        # Visual Acuity Count
        no_of_visual_acuity_created = VisualAcuity.objects.filter(screening_uuid__in=no_of_screening_created.values_list('uuid'),app_created_at__range=(start_date, end_date))
        no_of_visual_acuity_to_be_verfied = no_of_visual_acuity_created.filter(server_created_on__gt=start_date, status=3)

        # Glass Prescription Count
        no_of_glass_prescription_created = GlassPrescription.objects.filter(screening_uuid__in=no_of_screening_created.values_list('uuid'),app_created_at__range=(start_date, end_date))
        no_of_glass_prescription_to_be_verfied = no_of_glass_prescription_created.filter(server_created_on__gt=start_date, status=3)

        # Spectacle Type Count
        no_of_spectacle_type_created = SpectacleType.objects.filter(glass_prescription_uuid__in=no_of_glass_prescription_created.values_list('uuid'), app_created_at__range=(start_date, end_date))
        no_of_spectacle_type_to_be_verfied = no_of_spectacle_type_created.filter(server_created_on__gt=start_date, status=3)

        total_patient_count = no_of_patients_created.count()
        syn_patient_count = no_of_patients_to_be_verfied.count()
        total_screening_count = no_of_screening_created.count()
        syn_screening_count = no_of_screening_to_be_verfied.count()
        total_family_member_count = no_of_family_member_created.count()
        syn_family_member_count = no_of_family_member_to_be_verfied.count()
        total_visual_acuity_count = no_of_visual_acuity_created.count()
        syn_visual_acuity_count = no_of_visual_acuity_to_be_verfied.count()
        total_glass_prescription_count = no_of_glass_prescription_created.count()
        syn_glass_prescription_count = no_of_glass_prescription_to_be_verfied.count()
        total_spectacle_type_count = no_of_spectacle_type_created.count()
        syn_spectacle_type_count = no_of_spectacle_type_to_be_verfied.count()
        return total_patient_count, syn_patient_count, total_screening_count, syn_screening_count, total_family_member_count, syn_family_member_count,total_visual_acuity_count,syn_visual_acuity_count,total_glass_prescription_count,syn_glass_prescription_count,total_spectacle_type_count,syn_spectacle_type_count



class OrderRequest(BaseContent):
    STATUS_CHOICES = (
        (1,'Pending'),     
        (2,'Submited for Approval'),
        (3,'Approved'),
        (4,'Rejected'),
        (5,'Shipped'),
        (6,'Received'),
    )
    vision_center = models.ForeignKey(VisionCenter, on_delete=models.DO_NOTHING, null=True,blank=True)
    order_for = models.IntegerField(choices=((1,'Vision Center'),(2,'Camp')), null=True,blank=True)
    order_status = models.IntegerField(choices=STATUS_CHOICES, null=True,blank=True)
    approved_by =  models.ForeignKey(User, on_delete=models.DO_NOTHING,null= True,blank=True)
    approved_on = models.DateField(null=True,blank=True)
    camp = models.ForeignKey(Camp, on_delete=models.DO_NOTHING, null=True,blank=True)
    shippment_address = models.IntegerField(choices=((1,'Partner'),(2,'Camp'),(3,'Other'),(4,'Vision Center')),null=True,blank=True)
    other_address = models.TextField(null=True,blank=True)
    remark = models.TextField(null=True,blank=True)
    # custom_made = models.CharField(max_length=150, blank=True, null=True)
    donor = models.ForeignKey(Donor, on_delete=models.DO_NOTHING,null=True,blank=True)
    district = models.ForeignKey(District, on_delete=models.DO_NOTHING,null=True,blank=True)
    invoice_date = models.DateField(blank=True, null=True)
    invoice_no = models.CharField(max_length=150, blank=True, null=True)
    invoice_value = models.CharField(max_length=150, blank=True, null=True)
    courier_name = models.CharField(max_length=150, blank=True, null=True)
    awb_no = models.CharField(max_length=150, blank=True, null=True)

    class Meta:
        verbose_name_plural = "Order Request"
    
    def __str__(self):
        return self.created_by.username   

    
    def get_product(self):
        try:
            product=OrderRequestDetails.objects.filter(order_request_id=self.id).first()
        except ObjectDoesNotExist:
            product = None
        return product

    def get_frame(self):
        try:
            frame=OrderRequestDetails.objects.filter(order_request_id=self.id).first()
        except ObjectDoesNotExist:
            frame = None
        return frame

    def get_address(self):
        try:
            partner_address=UserPartnerLinkage.objects.get(user_id=self.created_by.id).partner
        except ObjectDoesNotExist:
            partner_address = None
        return partner_address
    
class OrderRequestDetails(BaseContent):

templates/user/add_user_link_to_role.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
<div class="row align-items-center">
  <div class="col-xl-12 mx-auto">
    <div class="card">
      <div class="card-body">
        <form method='POST' class="needs-validation" autocomplete="off" oninput='password2.setCustomValidity(password2.value != password.value ? "Passwords do not match." : "")' novalidate>
          {% csrf_token %}
          <div class='text-danger'>
              {{error}}
          </div>
          <div class="row mb-4">
            <label for="" class="col-md-2 col-form-label">User Name<span class="required-field"></span></label>
            <div class="col-md-4">
              <input type="text" id="username" class="form-control"  value="{% if user_obj.username %}{{ user_obj.username|default_if_none:'' }}{% else %}{{ username|default_if_none:'' }}{% endif %}" name="username" placeholder="Enter Username" required >
              <div class="invalid-feedback" id="username_vlu">
               
              </div>
            </div>
            <label for="" class="col-md-2 col-form-label"> Name<span class="required-field"></span></label>
            <div class="col-md-4">
              <input type="text" id="first_name" class="form-control"  value="{% if user_obj.first_name %}{{user_profile.user.first_name|default_if_none:''}}{% else %}{{ first_name|default_if_none:'' }}{% endif %}" name="first_name" placeholder="Enter Name" required>
              <div class="invalid-feedback">
                Please enter name.
              </div>
            </div>
          </div>
          <div class="row">
            <label for="email" class="col-md-2 col-form-label mb-4">Email<span class="required-field"></span></label>
            <div class="col-md-4 mb-4">
              <input type="email" id="email" class="form-control"  value="{% if user_obj.email %}{{ user_obj.email }}{% else %}{{ email|default_if_none:'' }}{% endif %}" name="email" placeholder="Enter Email id" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" required>
              <div class="invalid-feedback" id="email_vlu">
              </div>
            </div>
            {% if user_profile.role.id == 1 or user_profile.role.id == 2 or user_profile.role.id == 3 %}
            {% if  not heading_vpl %}
            <label for="" class="col-md-2 col-form-label mb-4">Role<span class="required-field"></span></label>
            <div class="col-md-4 mb-4">
              <select id="formrow-inputState" class="form-select" name='role' required>
                  <option selected="" value=''>Choose Role...{{role}}</option>
                  {% for role in userrole %}
                      <option value='{{ role.id }}' {% if role.id == user_profile.role.id %}selected{% endif %}>{{ role.name }}</option>
                  {% endfor %}
              </select>
              <div class="invalid-feedback">
                Please select role.
              </div>
            </div>
            {% endif %}
            {% endif %}
            {% if not user_profile %}
            <label for="" class="col-md-2 col-form-label mb-4">Password<span class="required-field"></span></label>
            <div class="col-md-4 mb-4">
              <input type="password" class="form-control" id="" name='password' value="{{password|default_if_none:''}}" placeholder="Enter Password" required >
              <div class="invalid-feedback">
                Please enter password.
              </div>
            </div>
            <label for="" class="col-md-2 col-form-label mb-4">Confirm Password<span class="required-field"></span></label>
            <div class="col-md-4 mb-4">
              <input type="password" class="form-control" id="" name='password2' value="{{password|default_if_none:''}}" placeholder="Confirm Password" required >
              <div class="invalid-feedback" id="val_password">
                
              </div>
            </div>
          </div>
          {% endif %}
          <div class="gap-2">
              <button type="reset" onclick="location.href='javascript:history.back()'" class="btn btn-secondary waves-effect">
                  Cancel
              </button>
              <button type="submit" id="submitting" style="margin-left: 5px;" class="btn btn-primary w-md">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div> 
</div>
<script src="{% static 'js/pages/form-validation.init.js' %}"></script> 
<script type="text/javascript">
var exit_email = '{{email_exist}}'
var user_exist = '{{user_exist}}'
if (exit_email){
  document.getElementById('email_vlu').style.display = 'block'
  document.getElementById('email_vlu').innerText = '{{email_exist}}'
}else{
  document.getElementById('email_vlu').innerText = 'Please enter email.'
}
if (user_exist){
  document.getElementById('username_vlu').style.display = 'block'
  document.getElementById('username_vlu').innerText = '{{user_exist}}'
}else{
  document.getElementById('username_vlu').innerText = 'Please enter username.'
}    
document.addEventListener('DOMContentLoaded', function() {
  document.getElementById('val_password').innerText = "Please enter password.";
  $("#password, #password2").keyup(function() {
    var password = document.getElementById('password').value;
    var password2 = document.getElementById('password2').value;
    if(password != password2){
      document.getElementById('val_password').innerText = "Passwords do not match.";
    }
  });
});
</script>   

{% endblock %}

templates/user/change_user_password.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
<div class="row align-items-center">
  <div class="col-xl-12 mx-auto">
    <div class="card">
      <div class="card-body">
        <form method="POST" class="needs-validation" autocomplete="off">
            {% csrf_token %}
            <div class="text-danger">
                {{ error }}
            </div>
            <div class="row mb-4">
                <label for="" class="col-md-2 col-form-label">Old Password<span class="required-field"></span></label>
                <div class="col-md-4">
                    <input type="password" class="form-control" name="old_password" placeholder="Enter your Old Password" required>
                </div>
            </div>
            <div class="row mb-4">
                <label for="" class="col-md-2 col-form-label">New Password<span class="required-field"></span></label>
                <div class="col-md-4">
                    <input type="password" class="form-control" name="password" placeholder="Enter your New Password" required>
                </div>
                <label for="" class="col-md-2 col-form-label">Confirm Password<span class="required-field"></span></label>
                <div class="col-md-4">
                    <input type="password" class="form-control" name="password2" placeholder="Confirm your New Password" required oninput="validatePassword()">
                </div>
            </div>
            <div class="gap-2">
                <button type="reset" onclick="location.href='javascript:history.back()'" class="btn btn-secondary waves-effect">
                    Cancel
                </button>
                <button type="submit" id="submitting" style="margin-left: 5px;" class="btn btn-primary w-md">Submit</button>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>

    
{% endblock %}
    

templates/user/edit_form.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}
<style>
    .error{
        color: red;
        list-style: none;
        display: contents;
        
    }
    .errorlist li::marker{
        display: none!important;
    }
    .errorlist  li{
        list-style: none;
    }
    .errorlist{
        padding: 0px!important;
    }
</style>
<div class="row align-items-center">
    <div class="col-xl-12 mx-auto">
        <div class="card">
            <div class="card-body">
                <form method='POST' class="needs-validation" autocomplete="off" novalidate>
                  {% csrf_token %}
                  {% if error %}
                  <div class="error">
                    {{ error }}
                    {{error_messages}}
                  </div>
                  {% endif %}
                  <div class="row "> 
                    {% for field in forms %}
                    <label for="" class="col-md-2 col-form-label mb-4" >
                        {% if field.field.required %}
                        {{field.label}}<span class="required-field"></span>
                        {% else %}
                        {{field.label}}
                        {% endif %}
                    </label>
                    <div class="col-md-4">
                        {{field}}
                        {% if field.errors %}
                          <div class="invalid-feedback">
                            {{ field.errors.0 }}
                          </div>
                        {% endif %}
                        {% if field.field.widget.input_type == 'select' %} 
                        <div class="invalid-feedback">
                          Please Choose {{field.label}} 
                        </div>
                        {% else %}
                        <div class="invalid-feedback" id="char_field" >
                          Please Enter {{field.label}}
                        </div>
                        {%  endif %}
                    </div>
                    {% endfor %}
                  </div>

                  <div class="mt-3">
                    <button type="reset" onclick="window.location.href='/list/{{model}}/'" class="btn btn-secondary waves-effect">
                        Cancel
                    </button>
                    <button type="submit" id="submitting" class="btn btn-primary w-md">Save</button>
                  </div>
                </form>
            </div>
            <!-- end card body -->
        </div>
        <!-- end card -->
    </div>
</div>
<script src="{% static 'libs/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'js/pages/form-validation.init.js' %}"></script> 

<script type="text/javascript">
    $(document).ready(function(){
        $('select').addClass('form-control')
        $('input').addClass('form-control')

    });
    
    $("#filter_reset").click(function() {
        $('#id_state').prop('selectedIndex', 0).change();
        this.form.submit();
    });
    $(document).ready(function() {
  $('#id_district').prop('readonly', true);

  $("#filter_reset").click(function() {
    $('#id_state').prop('selectedIndex', 0).change();
    this.form.submit();
  });
  $('#id_zone').change(function() {
    var optionSelected = $(this).find("option:selected");
    var valueSelected = optionSelected.val();

    $('#id_state').prop('readonly', false);

    if (valueSelected === "") {
    $('#id_state').prop('readonly', true);
    $("#id_state option").remove();
    } else {
    $.ajax({
        type: "GET",
        url: '/ajax/state/' + valueSelected + '/',
        success: function(result) {
        $("#id_state option").remove();
        a = '<option selected disabled value="">Choose State Name</option>';
        $("#id_state").append(a);

        if (JSON.parse(result) == 0) {
            $("#id_state option").remove();
            a = '<option selected value="">No state is mapped to this zone </option>';
            console.log(a)
            $("#id_state").append(a);
        } else {
            $.each(JSON.parse(result), function(key, value) {
            a = '<option value=' + value['id'] + '>' + value['name'] + '</option>';
            $("#id_state").append(a);
            });
        }
        }
    });
    }
});

$('#id_partner').change(function() {
    var optionSelected = $(this).find("option:selected");
    var valueSelected = optionSelected.val();

    $('#id_donor').prop('readonly', false);

    if (valueSelected === "") {
    $('#id_donor').prop('readonly', true);
    $("#id_donor option").remove();
    } else {
    $.ajax({
        type: "GET",
        url: '/ajax/donor/' + valueSelected + '/',
        success: function(result) {
        $("#id_donor option").remove();
        a = '<option selected disabled value="">Choose Donor Name</option>';
        $("#id_donor").append(a);

        if (JSON.parse(result) == 0) {
            $("#id_donor option").remove();
            a = '<option selected value="">No Donor is mapped to this Partner </option>';
            console.log(a)
            $("#id_donor").append(a);
        } else {
            $.each(JSON.parse(result), function(key, value) {
            a = '<option value=' + value['id'] + '>' + value['name'] + '</option>';
            $("#id_donor").append(a);
            });
        }
        }
    });
    }
});



  $('#id_state').change(function() {
    var optionSelected = $(this).find("option:selected");
    var valueSelected = optionSelected.val();

    $('#id_district').prop('readonly', false);

    if (valueSelected === "") {
      $('#id_district').prop('readonly', true);
      $("#id_district option").remove();
    } else {
      $.ajax({
        type: "GET",
        url: '/ajax/district/' + valueSelected + '/',
        success: function(result) {
          $("#id_district option").remove();
          a = '<option selected value="">Choose district Name</option>';
          $("#id_district").append(a);

          if (JSON.parse(result) == 0) {
            $("#id_district option").remove();
            a = '<option selected value="">No district is mapped to this state </option>';
            console.log(a)
            $("#id_district").append(a);
          } else {
            $.each(JSON.parse(result), function(key, value) {
              a = '<option value=' + value['id'] + '>' + value['name'] + '</option>';
              $("#id_district").append(a);
            });
          }
        }
      });
    }
  });
  // $('#id_state').trigger('change');

});


 
</script>
    
{% endblock %}

templates/user/edit_password.html
{% extends 'base.html' %}
{% load static %}
{% block contents %}
<div class="row align-items-center">
  <div class="col-xl-12 mx-auto">
    <div class="card">
      <div class="card-body">
        <form method='POST' class="needs-validation" autocomplete="off" oninput='password2.setCustomValidity(password2.value != password.value ? "Passwords do not match." : "")'>
          {% csrf_token %}
            <div class='text-danger'>
              {{error}}
            </div>
            <div class="row mb-4">
                <label for="" class="col-md-2 col-form-label">New Password<span class="required-field"></span></label>
                <div class="col-md-4">
                  <input type="password" class="form-control" id="" name='password'placeholder="Enter your NewPassword"  required >
                </div>
                <label for="" class="col-md-2 col-form-label">Confirm Password<span class="required-field"></span></label>
                <div class="col-md-4">
                  <input type="password" class="form-control" id="" name='password2' placeholder="Confirm your NewPassword" required >
                </div>
              </div>
              <div class="gap-2">
                <button type="reset" onclick="location.href='javascript:history.back()'" class="btn btn-secondary waves-effect">
                    Cancel
                </button>
                <button type="submit" id="submitting" style="margin-left: 5px;" class="btn btn-primary w-md">Submit</button>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>

    
{% endblock %}
    