Raahi/urls.py
from django.contrib import admin
from django.urls import include, re_path as url, path
from django.conf import settings
from django.views.static import serve
from .views import *
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('master_data.urls')),
    path('', include('sims.urls')),
    path('', include('dashboard.urls')),
    path('', login_view, name="login"),
    path('', include('reports.urls', namespace='reports')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('sidebar/', sidebar_view, name="sidebar"),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('dashboard/', dashboard, name="dashboard"),
    path('form_validate/', form_validate, name="form_validate"),
    path('send_login_email/', send_login_email, name="send_login_email"),
    url(r'^media/(?P<path>.*)$', serve,
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,
        {'document_root': settings.STATIC_ROOT}),

    
]

sims/urls.py
from django.urls import path
from .views import *
from . telecalling import *
from . orders import *

urlpatterns = [
    path('orderrequest_list/', orderrequest_list,name='orderrequest_list'),
    path('add_orderdetails/', add_orderdetails,name='add_orderdetails'),
    path('change_order_status/<str:model>/<int:id>/<str:action>/', change_order_status, name='change_order_status'),
    path('orderdelivery_list/', orderdelivery_list,name='orderdelivery_list'),
    path('add_deliverydetails/', add_deliverydetails,name='add_deliverydetails'),
    path('orders/', orders,name='orders'),
    path('edit_orders/<id>/', edit_orders,name='edit_orders'),
    path('update_order_status/<order_id>/<order_status_id>/', update_order_status,name='update_order_status'),
    path('add_orders/', add_orders,name='add_orders'),
    path('edit_orders_new/<id>/', edit_orders_new,name='edit_orders_new'),
    path('delete_orders/<id>/', delete_orders,name='delete_orders'),
    path('order_details_edit/<id>/', order_details_edit,name='order_details_edit'),
    path("ajax-reject/<reject_id>/<remark>", reject_remark, name="reject_remark"),
    path("add_invoice_awb_no/<order_id>/<invoice_no>/<awb_no>/<invoice_date>/<invoice_value>/<courier_name>/", add_invoice_awb_no, name="add_invoice_awb_no"),

    path('camp_list/', camp_list,name='camp_list'),
    path('camp_date_update/<camp_id>/<date>/<reason>/', camp_date_update,name='camp_date_update'),
    path('add_camp/', add_camp,name='add_camp'),
    path('edit_camp/<id>', edit_camp,name='edit_camp'),
    path('<id>/delete_camp/', delete_camp,name='delete_camp'),

    path('drop_check/', drop_check,name='drop_check'),
    path('order_receipt/', order_receipt,name='order_receipt'),
    path('edit_order_receipt/<id>/', edit_order_receipt,name='edit_order_receipt'),
    path('edit_deliverydetails/<id>/', edit_deliverydetails,name='edit_deliverydetails'),
    path('calculate_damagedetails/<order_id>/', calculate_damagedetails,name='calculate_damagedetails'),

    path('custom-order-request/', custom_order_request,name='custom_order_request'),
    path('generate-order-details/', generate_order_details,name='generate_order_details'),
    path('edit_orders_custom/<order_id>/', generate_order_details,name='edit_orders_custom'),
    path('update_custom_received/<order_id>/<invoice_nos>/', update_custom_received,name='update_custom_received'),
    
    # Patient
    path('patient_list/', patient_list,name='patient_list'),
    path('patient-details/<uuid>/', patient_details,name='patient_details'),
    path('screening_list/', screening_list,name='screening_list'),

    # Telecalling
    path('spectacle-list/', spectacle_list,name='spectacle_list'),
    path('spectacle-details/<uuid>/', spectacle_details,name='spectacle_details'),
    path('add-questions/', add_questions,name='add_questions'),
    path('cataract-list/', cataract_list,name='cataract_list'),
    path('cataract-details/<uuid>/', cataract_details,name='cataract_details'),
    path('cataract_patient-details/<uuid>/', cataract_patient_details,name='cataract_patient_details'),
    path('spectacle_patient-details/<uuid>/', spectacle_patient_details,name='spectacle_patient_details'),

    # Glass
    path('glass-list-pending/', glass_list_pending,name='glass_list_pending'),
    path('glass-list-ready/', glass_list_ready,name='glass_list_ready'),
    path('glass-list-delivered/', glass_list_delivered,name='glass_list_delivered'),
    path('update_glass_followup_status/<patient_id>/<followup_status_id>/', update_glass_followup_status,name='update_glass_followup_status'),

    path('qr-code/',qr_code_generation, name='qr_code_generation'),
    path('data-freeze/',data_freeze, name='data_freeze'),
    path('data-freeze-patients/<data_freeze_id>/',data_freezed_patients, name='data_freezed_patients'),
    path('approve-patient/<data_freeze_id>/', approve_patient,name='approve_patient'),
    path('export_order_details_to_excel/<int:order_id>/', export_order_details_to_excel, name='export_order_details_to_excel'),

]

sims/models.py
from django.db import models
from master_data.models import *
from django.contrib.auth.models import User, Group
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime, timedelta

# Create your models here.
YES_NO_CHOICE = (
        (1, 'YES'),
        (2, 'NO'),
        )

REPLY_CHOICE = (
        (1, 'YES'),
        (2, 'NO'),
        (3, 'NA'),
        )
class Product(BaseContent):
    name = models.CharField(max_length=150)

    class Meta:
        verbose_name_plural = "Product"

    def __str__(self):
        return self.name

class Camp(BaseContent):
    uuid = models.CharField(max_length=150, unique=True, db_index=True, null= True,blank=True)
    name = models.CharField(max_length=150)
    code = models.CharField(max_length=150)
    date = models.DateField() 
    ssmis_id = models.PositiveIntegerField(default=0,null=True, blank=True)
    location = models.CharField(max_length=150)
    address = models.CharField(max_length=150,null= True,blank=True)
    village = models.CharField(max_length=150,null= True,blank=True)
    block = models.CharField(max_length=150,null= True,blank=True)
    district = models.ForeignKey(District, on_delete=models.DO_NOTHING)
    expected_glass_prescription = models.CharField(max_length=150,null= True,blank=True)
    expected_refer_surgeries = models.CharField(max_length=150,null= True,blank=True)
    expected_camp_OPD = models.CharField(max_length=150,null= True,blank=True)
    donor = models.ForeignKey(Donor, on_delete=models.DO_NOTHING)
    vision_center = models.ForeignKey(VisionCenter, on_delete=models.DO_NOTHING,null= True,blank=True)
    coordinator_name =  models.CharField(max_length=150,null= True,blank=True)
    coordinator_mobile_no = models.CharField(max_length=10,null= True,blank=True)
    exclusive_camp = models.IntegerField(choices=YES_NO_CHOICE, default=1)
    partner = models.ForeignKey(Partner, on_delete=models.DO_NOTHING,null= True,blank=True)
    delay_reason = models.TextField(null=True,blank=True)
    start_time = models.TimeField(null=True,blank=True)
    end_time = models.TimeField(null=True,blank=True)
    
    class Meta:
        verbose_name_plural = "Camp"

    def __str__(self):
        return self.name    

    
    def get_start_end_date(self):
        try:
            patients = Patient.objects.filter(status=2,camp_id=self.id).order_by('server_created_on')
            if patients.exists():
                start_date = patients.first().server_created_on
                end_date = patients.last().server_created_on
                return start_date, end_date
            else:
                return None, None
        except ObjectDoesNotExist:
            return None, None

    def get_camp(self):
        try:
            camp = OrderRequest.objects.filter(camp_id=self.id).first()
        except ObjectDoesNotExist:
            camp = None
        return camp


    def get_approved_status(self):
        from dateutil.relativedelta import relativedelta
        current_date = datetime.now().date()
        syn_date = current_date + relativedelta(months=1)
        start_date = current_date.strftime('%Y-%m-06')
        end_date = syn_date.strftime('%Y-%m-05')
        
        no_of_patients_created = Patient.objects.filter(camp_id=self.id, app_created_at__range=(start_date, end_date))
        no_of_patients_to_be_verfied = no_of_patients_created.filter(server_created_on__gt=end_date, status=3)
        try:
            approved_status = no_of_patients_created.order_by('approved_on').first() 
        except:
            approved_status = None
        return approved_status

    def get_unsync_patient(self):
        current_date = datetime.now().date()        
        start_date = datetime(current_date.year, current_date.month, 1).date()
        next_month_start = datetime(current_date.year, current_date.month, 1) + timedelta(days=32)
        end_date = (next_month_start - timedelta(days=next_month_start.day)).date()
        try:
            product = Patient.objects.filter(camp_id=self.id)
        except ObjectDoesNotExist:
            product = None
        return product

    def get_syn_count(self):
        from dateutil.relativedelta import relativedelta
        current_date = datetime.now().date()
        syn_date = current_date + relativedelta(months=1)
        start_date = current_date.strftime('%Y-%m-06')
        end_date = syn_date.strftime('%Y-%m-05')
        
        no_of_patients_created = Patient.objects.filter(camp_id=self.id, app_created_at__range=(start_date, end_date))
        no_of_patients_to_be_verfied = no_of_patients_created.filter(server_created_on__gt=end_date, status=3)

        # Screening Count
        no_of_screening_created= Screening.objects.filter(patient_uuid__in=no_of_patients_created.values_list('uuid'),app_created_at__range=(start_date, end_date))
        no_of_screening_to_be_verfied = no_of_screening_created.filter(server_created_on__gt=end_date, status=3)

        # Family Member Count
        no_of_family_member_created = FamilyMember.objects.filter(screening_uuid__in=no_of_screening_created.values_list('uuid'),app_created_at__range=(start_date, end_date))
        no_of_family_member_to_be_verfied = no_of_family_member_created.filter(server_created_on__gt=start_date, status=3)

        # Visual Acuity Count
        no_of_visual_acuity_created = VisualAcuity.objects.filter(screening_uuid__in=no_of_screening_created.values_list('uuid'),app_created_at__range=(start_date, end_date))
        no_of_visual_acuity_to_be_verfied = no_of_visual_acuity_created.filter(server_created_on__gt=start_date, status=3)

        # Glass Prescription Count
        no_of_glass_prescription_created = GlassPrescription.objects.filter(screening_uuid__in=no_of_screening_created.values_list('uuid'),app_created_at__range=(start_date, end_date))
        no_of_glass_prescription_to_be_verfied = no_of_glass_prescription_created.filter(server_created_on__gt=start_date, status=3)

        # Spectacle Type Count
        no_of_spectacle_type_created = SpectacleType.objects.filter(glass_prescription_uuid__in=no_of_glass_prescription_created.values_list('uuid'), app_created_at__range=(start_date, end_date))
        no_of_spectacle_type_to_be_verfied = no_of_spectacle_type_created.filter(server_created_on__gt=start_date, status=3)

        total_patient_count = no_of_patients_created.count()
        syn_patient_count = no_of_patients_to_be_verfied.count()
        total_screening_count = no_of_screening_created.count()
        syn_screening_count = no_of_screening_to_be_verfied.count()
        total_family_member_count = no_of_family_member_created.count()
        syn_family_member_count = no_of_family_member_to_be_verfied.count()
        total_visual_acuity_count = no_of_visual_acuity_created.count()
        syn_visual_acuity_count = no_of_visual_acuity_to_be_verfied.count()
        total_glass_prescription_count = no_of_glass_prescription_created.count()
        syn_glass_prescription_count = no_of_glass_prescription_to_be_verfied.count()
        total_spectacle_type_count = no_of_spectacle_type_created.count()
        syn_spectacle_type_count = no_of_spectacle_type_to_be_verfied.count()
        return total_patient_count, syn_patient_count, total_screening_count, syn_screening_count, total_family_member_count, syn_family_member_count,total_visual_acuity_count,syn_visual_acuity_count,total_glass_prescription_count,syn_glass_prescription_count,total_spectacle_type_count,syn_spectacle_type_count



class OrderRequest(BaseContent):
    STATUS_CHOICES = (
        (1,'Pending'),     
        (2,'Submited for Approval'),
        (3,'Approved'),
        (4,'Rejected'),
        (5,'Shipped'),
        (6,'Received'),
    )
    vision_center = models.ForeignKey(VisionCenter, on_delete=models.DO_NOTHING, null=True,blank=True)
    order_for = models.IntegerField(choices=((1,'Vision Center'),(2,'Camp')), null=True,blank=True)
    order_status = models.IntegerField(choices=STATUS_CHOICES, null=True,blank=True)
    approved_by =  models.ForeignKey(User, on_delete=models.DO_NOTHING,null= True,blank=True)
    approved_on = models.DateField(null=True,blank=True)
    camp = models.ForeignKey(Camp, on_delete=models.DO_NOTHING, null=True,blank=True)
    shippment_address = models.IntegerField(choices=((1,'Partner'),(2,'Camp'),(3,'Other'),(4,'Vision Center')),null=True,blank=True)
    other_address = models.TextField(null=True,blank=True)
    remark = models.TextField(null=True,blank=True)
    # custom_made = models.CharField(max_length=150, blank=True, null=True)
    donor = models.ForeignKey(Donor, on_delete=models.DO_NOTHING,null=True,blank=True)
    district = models.ForeignKey(District, on_delete=models.DO_NOTHING,null=True,blank=True)
    invoice_date = models.DateField(blank=True, null=True)
    invoice_no = models.CharField(max_length=150, blank=True, null=True)
    invoice_value = models.CharField(max_length=150, blank=True, null=True)
    courier_name = models.CharField(max_length=150, blank=True, null=True)
    awb_no = models.CharField(max_length=150, blank=True, null=True)

    class Meta:
        verbose_name_plural = "Order Request"
    
    def __str__(self):
        return self.created_by.username   

    
    def get_product(self):
        try:
            product=OrderRequestDetails.objects.filter(order_request_id=self.id).first()
        except ObjectDoesNotExist:
            product = None
        return product

    def get_frame(self):
        try:
            frame=OrderRequestDetails.objects.filter(order_request_id=self.id).first()
        except ObjectDoesNotExist:
            frame = None
        return frame

    def get_address(self):
        try:
            partner_address=UserPartnerLinkage.objects.get(user_id=self.created_by.id).partner
        except ObjectDoesNotExist:
            partner_address = None
        return partner_address
    
class OrderRequestDetails(BaseContent):

templates/inventory/order_receipt/order_receipt_list.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link href="{% static 'libs/sweetalert2/dist/sweetalert2.min.css' %}" rel="stylesheet" type="text/css" />

<!-- DataTables -->
<link href="{% static 'libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet"
    type="text/css" />
<link href="{% static 'libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet"
    type="text/css" />

<!-- Responsive datatable examples -->
<link href="{% static 'libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet"
    type="text/css" />
{% endblock %}

{% block contents %}
{% csrf_token %}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form action="" method="get" class="mb-3">
                    <div class="row justify-content-end">
                        <div class="col-lg-3 mt-3">
                            <input type="search" name="search" class='form-control' value='{{search}}' placeholder='Search...'>
                        </div>
                        <div class="col-auto mt-3 ">
                            <button type="submit" class="form-control btn btn-outline-success waves-effect btn-xs float-right"><i class="fas fa-search" title="Search"></i></button>
                        </div>
                       
                    </div>
                </form> 
                <div class="table-responsive mb-3" data-pattern="priority-columns">
                    <table id="datatable-buttons" class="table  table-striped dt-responsive mb-0 mt-3">
                        <thead class="table-light" >
                            <tr>
                                <th> Order Id</th>
                                <th>Created By</th>   
                                <th>Created On</th>
                                <th>Product</th>
                                <th>Order For</th>
                                <th>Shippment Address</th>
                                <th>Order Status</th>
                            </tr>   
                        
                        </thead>
                        <tbody>
                            {% for l in data %}
                            <tr>                                    
                                <td><a href="/edit_order_receipt/{{l.id}}/"> {{l.id}}</a></td>
                                <td>{{l.created_by}}</td>
                                <td>{{l.server_created_on|date:"Y-m-d"}} </td>
                                <td>{{l.get_product.product|default_if_none:'-'}}</td>
                                <td>{{l.get_order_for_display|default_if_none:'-' }}</td>
                                <td>{{l.get_shippment_address_display|default_if_none:'-'}}</td>
                                <td>{{l.get_order_status_display}}</td>
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <nav aria-label="...">
                    {% if data.has_other_pages %}
                    <ul class="pagination justify-content-end " >
                        {% if data.has_previous %}
                        <li class="paginate_button page-item"><a class="page-link" href="?page=1">First</a></li>
                        {% else %}
                        <li class="paginate_button page-item disabled"><span class="page-link">First</span></li>
                        {% endif %}
                        {% for i in display_page_range %}
                            {% if data.number == i %}
                            <li class="page-item active" ><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                            {% else %}
                            <li class="paginate_button paginate_button page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if data.has_next %}
                            <li class="paginate_button page-item"><a class="page-link" href="?page={{ data.paginator.num_pages }}">Last</a></li>
                        {% else %}
                            <li class="paginate_button page-item disabled"><span class="page-link">Last</span></li>
                        {% endif %}
                        </ul>
                    {% endif %}
                </nav> 
            </div> 
        </div> 
    </div>
</div> 
{% endblock %}
{% block extra_javascript %}
<script src="{% static 'libs/sweetalert2/dist/sweetalert2.min.js' %}"></script>

<!-- Required datatable js -->
<script src="{% static 'libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<!-- <script src="{% static 'libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script> -->
<!-- Buttons examples -->
<script src="{% static 'libs/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>

<!-- Responsive examples -->
<script src="{% static 'libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

<!-- Datatable init js -->
<script src="{% static 'js/pages/datatables.init.js' %}"></script>

</script>
<script type="text/javascript" >
    function Confirm(id, model,title) {
        Swal.fire({
            title: "Are you sure!",
            text:"You want to "+ title +"?",
            showCancelButton: !0,
            confirmButtonColor: "#34c38f",
            cancelButtonColor: "#f46a6a",
            confirmButtonText: "Yes, "+ title +" it!",
        }).then((result) => {
            if (result.isConfirmed){
                // window.location.href = '/'+model+'/'+id+'/delete/';
                window.location.href = '/update_status/';
            };
                
        })
    };

</script>
{% endblock %}